### ISSUE TITLE
Create a template for requesting new spatial data

### ISSUE THREAD

**Issue by andybeet** [andybeet/NEFSCspatial#2]
Create an issue template for spatial data requests.
The template should include the following fields :

* The url to the location of the shapefiles
* What the shapefile represents
* Other info?

**Comment by kimberly-bastille** [comment]
@andybeet I do not have access to the settings tab in order to work on this issue. Could you adjust my access to this repo?

**Comment by andybeet** [comment]
not sure it is possible for someone else to have admin rights on a person account. Do you know if it is? If not we should migrate it to EDAB. Would that work? @kimberly-bastille

**Comment by kimberly-bastille** [comment]
Ya it seems like that would be the only way for me to get the correct access but lets hold off until other folks give there input.

**Comment by kimberly-bastille** [comment]
@andybeet if it makes the most sense to transfer directly to NEFSC it just means that I won't be able to create the template since that requires admin privileges. Not a huge deal. I vote move it directly.

**Comment by andybeet** [comment]
i see. well do you want to walk me through what you had in mind for the template and i'll do it prior to the transfer?

**Comment by kimberly-bastille** [comment]
@andybeet I was thinking it should be something like this. A madlib where everything bolded is a required field. This should supply us with all/most of the info we need in order to include it in the package. Let me know if I am missing anything. 

I would like to include  **DATASET NAME**  in the NEFSCspatial package. This data is available at **URL**. It is a **SHAPEFILE/RASTER/OTHER** showing the **DESCRIPTION**. It is at  **SCALE**. Documentation for the data is available at this **URL** and the point of contact is **NAME/EMAIL**.

**Comment by andybeet** [comment]
@kimberly-bastille. Can you take a look at these and let me know what i missed?https://github.com/andybeet/NEFSCspatial/issues/new/choose.

**Comment by kimberly-bastille** [comment]
@andybeet those look great! I think they are very clear and intuitive.
