### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jmhatch** [andybeet/NEFSCspatial#4]
Hi All,

I made some changes, but wanted to get feedback before I push said changes to the repo. I should of forked / pull requested my changes, that way someone with more experience could of looked them over (but I'm too lazy to make the switch now). So I thought I'd just ask my questions here, and then wait to push depending on the feedback.

1. I'd like to include raster data, which is another form of spatial data. I think we agreed this was OK, but just double checking. I made some changes to the documentation to include raster data. Also, the spatial data I'm going to include is in raster format.
2. I think `sf` and `raster` should be under `Depends:` in the `DESCRIPTION` file for `NEFSCspatial` (as opposed to `Suggests:`). I know this is unusual, but the data are being stored as `sf` or `raster` objects and it makes sense to load those pkgs too whenever our pkg is loaded. Otherwise the data may not be displayed as intended, if the user doesn't `library(sf); library(raster)` prior to loading our package. Or maybe under `Imports:`? Thoughts? I'm not sure.
3. I kept running into errors when I tried to build the documentation. It had to do with the file `R/data_Statistical_Areas_2010_withNames.R`. I think the error occurred b/c there is no corresponding dataset in the `data/` folder with the name `Statistical_Areas_2010_withNames`. If you delete that R file and then build the documentation, it works fine. Also, R automatically deletes the corresponding *.Rd file. Just an fyi.

**Comment by andybeet** [comment]
@jmhatch

So i agree. I think part of our process for adding content should be via pull requests. We then have two others look over pull requests and ok them. Don't worry about it now though.

1. I thought we said we weren't including raster data but i dont really remember. I dont really use it so i not sure as to how big those files are. Maybe @kimberly-bastille can help
2. I guess technically since this is a data package those packages aren't required, however you make a good point. Even though they are rda files without `sf` they do limit their use. So i'd say add them to `Imports`
3. I'll add the `Statistical_Areas_2010_withNames` shape file. I added the help as an example but forgot to add the data

**Comment by jmhatch** [comment]
Thanks, @andybeet! Yeah, getting a workflow outlined for adding content would be good. 

1. The raster data isn't large (it's a grid we use for other things), but I agree that larger raster data (like some environmental data) should be stored elsewhere. But the grid doesn't change and I think it fits the spirit of this R data pkg.
2. I'll add them to `Imports`. 
3. Thanks.

**Comment by kimberly-bastille** [comment]
1. I think it is fine to store fixed rasters in the package if their stored data size is less than 100MB. More than that and you won't be able to push it to GitHub. I initially thought no because the rasters I work with are ever-changing satellite data so I don't think this is appropriate to keep (sst for example) in our package.

**Comment by andybeet** [comment]
sounds good. thanks both
So can these files be stored as rda files? If so i say go ahead and add them.
If not then they'll need to go in `inst/extdata` folder

**Comment by jmhatch** [comment]
Yeah, rasters can be stored as rda files. Thanks, both.
